#!/usr/bin/env python3
"""Build the integrated Computers & Geosciences artwork manifest.

The publication-facing main figures are generated by ``build_vector_artwork``
and the PNGs are rendered from those exact vector PDFs.  This wrapper remains
the historical entry point used by CI and records the frozen analysis hashes;
it deliberately does not run the former Matplotlib main-figure pipeline,
whose output was visually different from the manuscript artwork.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pymupdf
from matplotlib import font_manager
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
from PIL import Image

CANONICAL_FONT_DIR = Path(__file__).resolve().parent / "fonts"
CANONICAL_FONT_SHA256 = {
    "DejaVuSans.ttf": "7da195a74c55bef988d0d48f9508bd5d849425c1770dba5d7bfc6ce9ed848954",
    "DejaVuSans-Bold.ttf": "e6476c1b80502924294eed40894c5b18e06c181444ca953e5334262df9c27724",
}


def configure_canonical_matplotlib_fonts() -> None:
    """Force supplementary PDFs to embed the same redistributed font files."""

    font_manager.fontManager.ttflist = [
        entry
        for entry in font_manager.fontManager.ttflist
        if entry.name != "DejaVu Sans"
    ]
    for name, expected_sha256 in CANONICAL_FONT_SHA256.items():
        path = CANONICAL_FONT_DIR / name
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected_sha256:
            raise ValueError(f"Canonical Matplotlib font hash mismatch: {path}")
        font_manager.fontManager.addfont(path)
    font_manager.fontManager._findfont_cached.cache_clear()
    for weight, name in (("normal", "DejaVuSans.ttf"), ("bold", "DejaVuSans-Bold.ttf")):
        resolved = Path(
            font_manager.findfont(
                font_manager.FontProperties(family="DejaVu Sans", weight=weight),
                fallback_to_default=False,
            )
        ).resolve()
        if resolved != (CANONICAL_FONT_DIR / name).resolve():
            raise RuntimeError(f"Matplotlib resolved a non-canonical font: {resolved}")


configure_canonical_matplotlib_fonts()

matplotlib.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "axes.titlesize": 12,
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
    }
)

# Matplotlib otherwise writes the current time into every PDF's Info
# dictionary.  That makes a fresh CI checkout appear dirty after regeneration
# even when the plotted content is unchanged.
PDF_METADATA = {
    "Title": "GeoLogParser Paper 4 figure",
    "Author": "Yifan Du",
    "Subject": "Provenance-grounded selective assurance for borehole database ingestion",
    "Creator": "GeoLogParser deterministic figure builder",
    "Producer": "Matplotlib",
    "CreationDate": None,
    "ModDate": None,
}


ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "figures"
MODERN = ROOT / "experiments/paper1/analysis/modern_vlm_statistics_v001.json"
ASSURANCE = ROOT / "experiments/paper2/analysis/vlm_proposal_assurance_v001.json"
SPATIAL = ROOT / "experiments/paper3/analysis/swissgeol_spatial_sensitivity_v001.json"
P2_ABLATION = ROOT / "experiments/paper2/analysis/california_candidate_pool_ablation_v001.json"
P2_RISK = ROOT / "experiments/paper2/analysis/california_document_risk_v001.json"
P2_THRESHOLD = ROOT / "experiments/paper2/analysis/california_risk_threshold_curve_v001.json"
P3_CONTROLLED = (
    ROOT
    / "publication_evidence/result_core/results/2026-08-14/"
    / "P3_SWISSGEOL_ERROR_CLASS_PROPAGATION_002/metrics.json"
)
SUPPLEMENT_RASTER_DPI = 600
SUPPLEMENTARY_ARTWORK = {
    "Supplementary_Figure_S1.pdf": "F4_risk_coverage_frontier.png",
    "Supplementary_Figure_S2.pdf": "F5_threshold_development_curve.png",
    "Supplementary_Figure_S3.pdf": "F7_controlled_error_mechanisms.png",
}


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def style(ax) -> None:
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="y", color="#d8dee9", linewidth=0.6, alpha=0.7)
    ax.set_axisbelow(True)


def render_pdf_to_png(pdf_path: Path, png_path: Path, dpi: int) -> None:
    with pymupdf.open(pdf_path) as document:
        if len(document) != 1:
            raise ValueError(f"Expected one page in {pdf_path}")
        pixmap = document[0].get_pixmap(
            dpi=dpi,
            colorspace=pymupdf.csRGB,
            alpha=False,
        )
    image = Image.frombytes("RGB", (pixmap.width, pixmap.height), pixmap.samples)
    image.save(
        png_path,
        format="PNG",
        dpi=(dpi, dpi),
        optimize=False,
        compress_level=9,
    )


def build_supplementary_artwork() -> None:
    from geologparser.paper_figures import (
        save_controlled_error_class_propagation,
        save_paper2_sequence_risk,
        save_paper2_threshold_curve,
    )

    save_paper2_sequence_risk(
        P2_ABLATION,
        P2_RISK,
        OUT / "Supplementary_Figure_S1.pdf",
        metadata=PDF_METADATA,
    )
    save_paper2_threshold_curve(
        P2_THRESHOLD,
        OUT / "Supplementary_Figure_S2.pdf",
        metadata=PDF_METADATA,
    )
    controlled_result_dir = P3_CONTROLLED.parent.relative_to(ROOT).as_posix()
    save_controlled_error_class_propagation(
        [
            {
                "experiment_id": "P3_SWISSGEOL_ERROR_CLASS_PROPAGATION_002",
                "result_path": controlled_result_dir,
            }
        ],
        ROOT,
        OUT / "Supplementary_Figure_S3.pdf",
        metadata=PDF_METADATA,
    )
    for pdf_name, png_name in SUPPLEMENTARY_ARTWORK.items():
        render_pdf_to_png(
            OUT / pdf_name,
            OUT / png_name,
            SUPPLEMENT_RASTER_DPI,
        )


def fig1() -> None:
    fig, ax = plt.subplots(figsize=(13.0, 4.8), dpi=180)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    nodes = [
        (0.03, 0.42, 0.16, 0.28, "Modern VLM proposal", "high-recall\nimage -> intervals", "#dbeafe"),
        (0.235, 0.42, 0.16, 0.28, "Independent evidence", "positioned values\npage + bbox", "#dcfce7"),
        (0.44, 0.42, 0.16, 0.28, "Deterministic checks", "units; order\ncolumn ownership", "#fef3c7"),
        (0.625, 0.55, 0.17, 0.22, "ACCEPT", "auditable row", "#bbf7d0"),
        (0.625, 0.28, 0.17, 0.22, "NEEDS\nREVIEW", "raw proposal +\nreason preserved", "#fee2e2"),
        (0.82, 0.42, 0.17, 0.28, "Database + support", "accepted rows ->\nsupport mask", "#e0e7ff"),
        (0.44, 0.08, 0.16, 0.18, "Legacy recovery", "secondary harm\nanalysis only", "#f1f5f9"),
    ]
    for x, y, w, h, title, body, color in nodes:
        linestyle = "--" if title == "Legacy recovery" else "-"
        box = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.012,rounding_size=0.02",
                             linewidth=1.2, linestyle=linestyle, edgecolor="#334155", facecolor=color)
        ax.add_patch(box)
        ax.text(x + w / 2, y + h * 0.64, title, ha="center", va="center", fontsize=11.8,
                fontweight="bold", color="#0f172a")
        ax.text(x + w / 2, y + h * 0.34, body, ha="center", va="center", fontsize=9.8,
                color="#334155")
    arrows = [
        ((0.19, 0.56), (0.235, 0.56)), ((0.395, 0.56), (0.44, 0.56)),
        ((0.60, 0.56), (0.625, 0.66)), ((0.60, 0.56), (0.625, 0.39)),
        ((0.795, 0.66), (0.82, 0.56)), ((0.795, 0.39), (0.82, 0.56)),
    ]
    for start, end in arrows:
        ax.add_patch(FancyArrowPatch(start, end, arrowstyle="-|>", mutation_scale=14,
                                     linewidth=1.3, color="#475569"))
    ax.add_patch(FancyArrowPatch((0.52, 0.42), (0.52, 0.26), arrowstyle="-|>",
                                 mutation_scale=12, linewidth=1.1,
                                 linestyle="--", color="#64748b"))
    ax.text(0.03, 0.78, "RQ1 / CAPABILITY", ha="left", fontsize=10,
            fontweight="bold", color="#1d4ed8")
    ax.text(0.235, 0.78, "RQ2 / ASSURANCE", ha="left", fontsize=10,
            fontweight="bold", color="#15803d")
    ax.text(0.82, 0.78, "RQ3 / CONSEQUENCE", ha="left", fontsize=10,
            fontweight="bold", color="#4338ca")
    ax.text(0.5, 0.91, "One chain: capability -> evidence -> decision -> support consequence",
            ha="center", fontsize=14, fontweight="bold", color="#0f172a")
    ax.text(0.5, 0.02, "Dashed branch: legacy sequence reconstruction is secondary harm analysis, not the main assurance path.",
            ha="center", fontsize=9.2, color="#475569")
    fig.tight_layout()
    fig.savefig(OUT / "F1_trustworthy_framework.png", dpi=300, bbox_inches="tight")
    fig.savefig(OUT / "F1_trustworthy_framework.pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def fig2() -> None:
    d = load(MODERN)
    keys = [value for value in d["analyses"].values() if "CALIFORNIA" in value["experiment_id"]]
    keys.sort(key=lambda x: int(x["cohort"].split("v")[1]))
    cohorts = [x["cohort"].replace("California v", "v") for x in keys]
    qwen = [x["document_cluster_metrics"]["f1"] for x in keys]
    rapid = [x["paired_against_frozen_rapidocr"]["right"]["f1"] for x in keys]
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12.8, 5.0), dpi=180,
                                   gridspec_kw={"width_ratios": [1.25, 1]})
    x = np.arange(len(cohorts))
    width = 0.36
    ax1.bar(x - width / 2, qwen, width, color="#2563eb", label="Qwen3.8-27B-FP8")
    ax1.bar(x + width / 2, rapid, width, color="#94a3b8", label="RapidOCR positioned")
    ax1.set_ylim(0, 1.0)
    ax1.set_ylabel("Boundary-pair interval F1")
    ax1.set_xticks(x, cohorts)
    ax1.set_title("Familiar source: five record-disjoint cohorts", fontweight="bold", pad=12)
    ax1.text(0.02, 0.97, "Published manual-transcription Gold",
             transform=ax1.transAxes, va="top", fontsize=9.2, color="#334155")
    ax1.legend(
        frameon=False, fontsize=9, loc="upper center", ncol=2,
        bbox_to_anchor=(0.5, -0.14),
    )
    style(ax1)
    for i, v in enumerate(qwen):
        ax1.text(i - width / 2, v + 0.025, f"{v:.3f}", ha="center", fontsize=9, color="#1d4ed8")
    ax2_labels = ["Swiss-Qwen", "Swiss-OCR", "Swiss-Tess.", "BGS-OCR", "BGS-Tess.", "Raft-OCR"]
    ax2_values = [0.576923, 0.679, 0.857, 0.0379, 0.0405, 1.000]
    colors = ["#2563eb", "#94a3b8", "#64748b", "#cbd5e1", "#cbd5e1", "#64748b"]
    x2 = np.arange(len(ax2_labels))
    ax2.bar(x2, ax2_values, color=colors)
    ax2.set_ylim(0, 1.0)
    ax2.set_ylabel("Boundary-pair interval F1")
    ax2.set_xticks(x2, ax2_labels, fontsize=9)
    ax2.set_title("Source shift: declared evidence tiers", fontweight="bold", pad=12)
    ax2.text(0.02, 0.97, "Source-agreement/stress panels; not pooled with Gold",
             transform=ax2.transAxes, va="top", fontsize=9.2, color="#334155")
    style(ax2)
    for i, v in enumerate(ax2_values):
        ax2.text(i, min(v + 0.035, 0.97), f"{v:.3f}", ha="center", fontsize=9)
    fig.suptitle("Capability and transport are separate evidence questions", fontsize=14, fontweight="bold")
    fig.tight_layout(rect=(0, 0.08, 1, 0.93), w_pad=2.0)
    fig.savefig(OUT / "F2_vlm_source_shift.png", dpi=300, bbox_inches="tight")
    fig.savefig(OUT / "F2_vlm_source_shift.pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def fig3() -> None:
    d = load(ASSURANCE)
    rows = {row["cohort"]: row for row in d["analyses"]}
    names = ["v001\ndev", "v002\nvalidation", "v003\nheld-out"]
    point_labels = ["dev", "validation", "held-out"]
    keys = ["California v001", "California v002", "California v003"]
    precision = [rows[k]["point_estimates"]["accepted_precision"] for k in keys]
    coverage = [rows[k]["point_estimates"]["accepted_coverage"] for k in keys]
    raw_p = [rows[k]["point_estimates"]["raw_precision"] for k in keys]
    complete = [rows[k]["complete_document_auto_acceptance"]["value"] for k in keys]
    # Use the committed public evidence projection rather than the controlled
    # local result store so fresh-clone CI can regenerate this figure.
    heldout_metrics = load(
        ROOT / "publication_evidence/result_core/results/2026-08-17/"
        "P2_VLM_PROPOSAL_ASSURANCE_CALIFORNIA_V003_HELDOUT_002/metrics.json"
    )
    proposals = heldout_metrics["proposal_count"]
    accepted = heldout_metrics["accepted_proposal_coverage"]["numerator"]
    endpoint_anchor = heldout_metrics["same_page_numeric_anchor_coverage"]
    both_anchors = heldout_metrics["complete_interval_numeric_anchor_coverage"]
    top_anchor = heldout_metrics["top_numeric_anchor_coverage"]
    bottom_anchor = heldout_metrics["bottom_numeric_anchor_coverage"]
    fig = plt.figure(figsize=(12.8, 6.8), dpi=180)
    grid = fig.add_gridspec(2, 2, height_ratios=[1, 1.1], hspace=0.42, wspace=0.28)
    ax1 = fig.add_subplot(grid[0, 0])
    ax2 = fig.add_subplot(grid[0, 1])
    ax3 = fig.add_subplot(grid[1, :])
    ax1.plot(coverage, precision, "o-", color="#16a34a", linewidth=2, label="selective")
    ax1.scatter([1.0], [raw_p[-1]], color="#64748b", marker="x", s=60, label="raw baseline")
    offsets = [(-28, -8), (4, -18), (16, -6)]
    for x, y, label, offset in zip(coverage, precision, point_labels, offsets):
        ax1.annotate(label, (x, y), xytext=offset, textcoords="offset points", fontsize=9)
    ax1.set_xlim(0, 1.05); ax1.set_ylim(0.80, 1.01)
    ax1.set_xlabel("Proposal coverage (accepted / proposed)")
    ax1.set_ylabel("Selective precision")
    ax1.set_title("Precision versus proposal coverage", fontweight="bold", pad=10)
    style(ax1); ax1.legend(frameon=False, fontsize=9, loc="lower left")
    ax2.bar(np.arange(3), np.array(complete) * 100, color="#f59e0b")
    ax2.set_ylim(0, 100); ax2.set_xticks(np.arange(3), names)
    ax2.set_ylabel("Complete documents auto-accepted (%)")
    ax2.set_title("Complete-document utility", fontweight="bold", pad=10)
    style(ax2)
    for i, v in enumerate(complete): ax2.text(i, v * 100 + 3, f"{int(v*100)}%", ha="center", fontsize=10)
    stages = ["VLM interval proposals", "Both endpoints anchored", "Owned and accepted", "Complete documents"]
    values = [proposals, both_anchors["numerator"], accepted, rows[keys[-1]]["complete_document_auto_acceptance"]["numerator"]]
    y = np.arange(len(stages))
    ax3.barh(y, values, color=["#2563eb", "#60a5fa", "#16a34a", "#f59e0b"], height=0.58)
    ax3.set_yticks(y, stages); ax3.invert_yaxis(); ax3.set_xlabel("Count (held-out v003)")
    ax3.set_title("Evidence funnel", fontweight="bold", pad=10)
    style(ax3)
    for yi, v in zip(y, values): ax3.text(v + max(values) * 0.02, yi, str(v), va="center", fontsize=10)
    ax3.text(
        0.0, -0.25,
        "Endpoint-field anchors: top %s/%s; bottom %s/%s; total %s/%s = %.1f%%\n"
        "Both-endpoint anchoring is the interval-level funnel stage."
        % (
            top_anchor["numerator"], top_anchor["denominator"],
            bottom_anchor["numerator"], bottom_anchor["denominator"],
            endpoint_anchor["numerator"], endpoint_anchor["denominator"],
            endpoint_anchor["value"] * 100,
        ),
        transform=ax3.transAxes, va="top", fontsize=9, color="#475569",
    )
    fig.suptitle("Selective assurance makes automation utility explicit", fontsize=14, fontweight="bold")
    fig.tight_layout(rect=(0, 0.02, 1, 0.95))
    fig.savefig(OUT / "F3_assurance_frontier.png", dpi=300, bbox_inches="tight")
    fig.savefig(OUT / "F3_assurance_frontier.pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def fig4() -> None:
    d = load(SPATIAL)
    fs = d["full_support_comparison"]
    ms = d["matched_subset_comparison"]
    labels = ["raw", "reread", "risk"]
    full = [fs[k]["aggregate"]["relative_absolute_volume_error"] for k in labels]
    matched = [ms[k]["aggregate"]["relative_absolute_volume_error"] for k in labels]
    support = {row["variant"]: row for row in d["spatial_support"] if row["boundary_index"] == 1}
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(13.2, 5.0), dpi=180,
                                      gridspec_kw={"width_ratios": [1.35, 0.85, 1]})
    x = np.arange(3); width = 0.36
    method_colors = {"raw": "#64748b", "reread": "#2563eb", "risk": "#dc2626"}
    ax1.bar(x - width / 2, full, width, color=[method_colors[k] for k in labels], label="Full-support")
    ax1.bar(x + width / 2, matched, width, color=[method_colors[k] for k in labels],
            hatch="//", edgecolor="#ffffff", linewidth=0.8, label="Matched-subset (15 docs)")
    ax1.set_xticks(x, labels); ax1.set_ylabel("Reference-relative volume discrepancy")
    ax1.set_ylim(0, 0.17); ax1.set_title("Distinct estimands", fontweight="bold")
    ax1.text(0.02, 0.97, "Solid = full support; hatched = matched subset",
             transform=ax1.transAxes, va="top", fontsize=9, color="#334155")
    ax1.legend(frameon=False, fontsize=9, loc="upper right"); style(ax1)
    for i, (a, b) in enumerate(zip(full, matched)):
        ax1.text(i - width / 2, a + 0.006, f"{a:.4f}", ha="center", fontsize=9)
        ax1.text(i + width / 2, b + 0.006, f"{b:.4f}", ha="center", fontsize=9)
    raw_hull = support["raw"]["convex_hull_area_ratio"]
    risk_hull = support["risk"]["convex_hull_area_ratio"]
    ax2.bar([0 - width / 2, 0 + width / 2], [raw_hull, risk_hull], width,
            color=[method_colors["raw"], method_colors["risk"]])
    ax2.set_xticks([0 - width / 2, 0 + width / 2], ["raw", "risk-aware"])
    ax2.set_ylim(0, 1.05); ax2.set_ylabel("Hull area ratio")
    ax2.set_title("Support retained", fontweight="bold"); style(ax2)
    ax2.text(0 - width / 2, raw_hull + 0.04, f"{raw_hull:.3f}", ha="center", fontsize=9)
    ax2.text(0 + width / 2, risk_hull + 0.04, f"{risk_hull:.3f}", ha="center", fontsize=9)
    dist_names = ["Mean nearest\nneighbour", "Mean grid-to-\nobservation"]
    raw_dist = [support["raw"]["nearest_neighbour_distance_m"]["mean"] / 1000,
                support["raw"]["grid_to_nearest_observation_distance_m"]["mean"] / 1000]
    risk_dist = [support["risk"]["nearest_neighbour_distance_m"]["mean"] / 1000,
                 support["risk"]["grid_to_nearest_observation_distance_m"]["mean"] / 1000]
    ax3.bar(np.arange(2) - width / 2, raw_dist, width, color=method_colors["raw"], label="raw")
    ax3.bar(np.arange(2) + width / 2, risk_dist, width, color=method_colors["risk"], label="risk-aware")
    ax3.set_xticks(np.arange(2), dist_names); ax3.set_ylabel("Distance (km)")
    ax3.set_title("Support spacing", fontweight="bold")
    ax3.legend(frameon=False, fontsize=9); style(ax3)
    fig.suptitle("Abstention changes the geoscientific observation set", fontsize=14, fontweight="bold")
    fig.tight_layout(rect=(0, 0.04, 1, 0.94), w_pad=1.5)
    fig.savefig(OUT / "F4_spatial_support_consequence.png", dpi=300, bbox_inches="tight")
    fig.savefig(OUT / "F4_spatial_support_consequence.pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def graphical_abstract() -> None:
    fig, ax = plt.subplots(figsize=(12.5, 4.2), dpi=220)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    nodes = [
        (0.03, 0.35, 0.14, 0.30, "Borehole page", "visual record", "#e2e8f0"),
        (0.22, 0.35, 0.14, 0.30, "VLM proposal", "high recall", "#dbeafe"),
        (0.41, 0.35, 0.14, 0.30, "Independent\n evidence", "page + bbox", "#dcfce7"),
        (0.60, 0.53, 0.13, 0.22, "ACCEPT", "auditable row", "#bbf7d0"),
        (0.60, 0.25, 0.13, 0.22, "NEEDS_REVIEW", "preserve reason", "#fee2e2"),
        (0.79, 0.35, 0.16, 0.30, "Database +\nspatial support", "support mask", "#e0e7ff"),
    ]
    for x, y, w, h, title, body, color in nodes:
        ax.add_patch(FancyBboxPatch((x, y), w, h,
                                    boxstyle="round,pad=0.012,rounding_size=0.018",
                                    linewidth=1.1, edgecolor="#334155",
                                    facecolor=color))
        ax.text(x + w / 2, y + h * 0.63, title, ha="center", va="center",
                fontsize=11, fontweight="bold", color="#0f172a")
        ax.text(x + w / 2, y + h * 0.34, body, ha="center", va="center",
                fontsize=9, color="#334155")
    for start, end in [
        ((0.17, 0.50), (0.22, 0.50)), ((0.36, 0.50), (0.41, 0.50)),
        ((0.55, 0.50), (0.60, 0.64)), ((0.55, 0.50), (0.60, 0.36)),
        ((0.73, 0.64), (0.79, 0.50)), ((0.73, 0.36), (0.79, 0.50)),
    ]:
        ax.add_patch(FancyArrowPatch(start, end, arrowstyle="-|>",
                                     mutation_scale=14, linewidth=1.3,
                                     color="#475569"))
    ax.text(0.50, 0.90,
            "From visual extraction to trustworthy database ingestion",
            ha="center", fontsize=15, fontweight="bold", color="#0f172a")
    ax.text(0.50, 0.07,
            "0.993 precision @ 24.4% proposal coverage  |  4/100 complete documents auto-accepted",
            ha="center", fontsize=10, color="#334155")
    fig.tight_layout()
    fig.savefig(OUT / "graphical_abstract.png", dpi=300, bbox_inches="tight")
    fig.savefig(OUT / "graphical_abstract.pdf", bbox_inches="tight", metadata=PDF_METADATA)
    plt.close(fig)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    try:
        from build_vector_artwork import (
            FONT_DIR,
            FONT_FILES,
            PRIMARY_ARTWORK,
            RASTER_DPI,
            main as build_vector_artwork,
        )
    except ImportError:  # pragma: no cover - package import path for callers
        from papers.paper4.build_vector_artwork import (  # type: ignore
            FONT_DIR,
            FONT_FILES,
            PRIMARY_ARTWORK,
            RASTER_DPI,
            main as build_vector_artwork,
        )

    # Figure_*.pdf is the canonical artwork used by manuscript.tex.  The
    # vector builder also emits the matching descriptive PNG derivatives and
    # graphical abstract before this manifest is written.
    build_vector_artwork()
    build_supplementary_artwork()
    manifest = {
        "manuscript": "paper4",
        "status": "integrated_cg_main_figure_set",
        "canonical_artwork": {
            "source_format": "single-page PDF",
            "raster_renderer": "PyMuPDF",
            "raster_dpi": RASTER_DPI,
            "policy": "PNG files are lossless RGB derivatives of the exact PDF pages used by manuscript.tex.",
            "embedded_font_sources": {
                (FONT_DIR / name).relative_to(ROOT).as_posix(): expected_sha256
                for name, expected_sha256 in FONT_FILES.items()
            },
        },
        "figures": [
            {"id": "F1", "file": "figures/F1_trustworthy_framework.png", "vector_file": "figures/Figure_1.pdf", "purpose": "provenance-grounded assurance framework", "caption": "Provenance-grounded assurance framework."},
            {"id": "F2", "file": "figures/F2_vlm_source_shift.png", "vector_file": "figures/Figure_2.pdf", "purpose": "California VLM/OCR comparison and source shift", "caption": "Modern VLM reliability across California cohorts and source shift."},
            {"id": "F3", "file": "figures/F3_assurance_frontier.png", "vector_file": "figures/Figure_3.pdf", "purpose": "precision, coverage, and complete-document automation", "caption": "Selective assurance viewed simultaneously as precision, proposal coverage, complete-document automation, and a held-out v003 evidence funnel."},
            {"id": "F4", "file": "figures/F4_spatial_support_consequence.png", "vector_file": "figures/Figure_4.pdf", "purpose": "full-support versus matched-support downstream consequence", "caption": "Full-support versus matched-support downstream consequence of selective acceptance."},
        ],
        "graphical_abstract": {
            "file": "figures/graphical_abstract.pdf",
            "raster_file": "figures/graphical_abstract.png",
            "purpose": "schematic overview of proposal, evidence, decision, and support",
            "rights": "programmatic schematic; no source-page image used",
        },
        "vector_exports": [
            "figures/Figure_1.pdf",
            "figures/Figure_2.pdf",
            "figures/Figure_3.pdf",
            "figures/Figure_4.pdf",
        ],
        "rights_linkage": (
            "All programmatic artwork was reviewed by the sole author for public "
            "dissemination; no source-page image is embedded in the main figures or "
            "graphical abstract."
        ),
        "supplementary_figures": [
            {"id": "S1", "file": "figures/F4_risk_coverage_frontier.png", "vector_file": "figures/Supplementary_Figure_S1.pdf", "raster_dpi": SUPPLEMENT_RASTER_DPI, "purpose": "legacy sequence risk frontier", "caption": "Legacy sequence-reconstruction risk frontier."},
            {"id": "S2", "file": "figures/F5_threshold_development_curve.png", "vector_file": "figures/Supplementary_Figure_S2.pdf", "raster_dpi": SUPPLEMENT_RASTER_DPI, "purpose": "development-only threshold curve", "caption": "Development-only threshold selection."},
            {"id": "S3", "file": "figures/F7_controlled_error_mechanisms.png", "vector_file": "figures/Supplementary_Figure_S3.pdf", "raster_dpi": SUPPLEMENT_RASTER_DPI, "purpose": "controlled synthetic perturbation mechanisms", "caption": "Controlled error mechanisms and spatial response."},
        ],
        "source_manifests": {
            p.relative_to(ROOT).as_posix(): digest(p)
            for p in [
                MODERN,
                ASSURANCE,
                ROOT / "publication_evidence/result_core/results/2026-08-17/"
                "P2_VLM_PROPOSAL_ASSURANCE_CALIFORNIA_V003_HELDOUT_002/metrics.json",
                SPATIAL,
                P2_ABLATION,
                P2_RISK,
                P2_THRESHOLD,
                P3_CONTROLLED,
            ]
        },
    }
    # This manifest is committed and hash-audited, so bypass platform newline
    # conversion and always emit UTF-8 with LF line endings.
    (Path(__file__).resolve().parent / "figure_manifest.json").write_bytes(
        (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    )


if __name__ == "__main__":
    main()
