#!/usr/bin/env python3
"""Build the pre-submission source and licence verification ledger.

The ledger is deliberately separate from ``data_registry.yaml``.  The registry
describes discovery/acquisition; this ledger records every source that can
appear in an experiment, including sources whose rights or content review is
still unresolved.  It binds local material to immutable manifest hashes so a
human can repeat the final rights check before submission.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import date
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = Path("/data/GeoLogParser")


LOCAL_DIRS = {
    "mendeley_sedlog_drilling_cores_v002": DATA_ROOT / "datasets/public/mendeley_sedlog_drilling_cores_v002",
    "mendeley_subsurface_slopes_logs_v001": DATA_ROOT / "datasets/public/mendeley_subsurface_slopes_logs_v001",
    "mendeley_tiber_borehole_pdf_v001": DATA_ROOT / "datasets/public/mendeley_tiber_borehole_pdf_v001",
    "mendeley_guaiba_cores_pdf_v001": DATA_ROOT / "datasets/public/mendeley_guaiba_cores_pdf_v001",
    "unipd_levee_geotechnical_logs_v001": DATA_ROOT / "datasets/public/unipd_levee_geotech_v001",
    "unipd_levee_geotech_v001": DATA_ROOT / "datasets/public/unipd_levee_geotech_v001",
    "mendeley_borehole_log_collection_v002": DATA_ROOT / "datasets/public/mendeley_borehole_logs_v002",
    "bgs_onshore_borehole_records": DATA_ROOT / "datasets/public/bgs_v001",
    "mendeley_binhai_cptu_borehole_v002": DATA_ROOT / "datasets/public/mendeley_binhai_cptu_borehole_v002",
    "mendeley_coal_boreholes_602_v001": DATA_ROOT / "datasets/public/mendeley_coal_boreholes_602_v001",
}

LOCAL_DIRS["synthetic_borehole_logs_v001"] = DATA_ROOT / "datasets/synthetic_borehole_logs_v001"
LOCAL_DIRS["chinese_engineering_borehole_logs"] = DATA_ROOT / "datasets/candidates_quarantine/chinese_public_web_20260812"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def inventory(path: Path) -> tuple[list[str], str | None, list[dict[str, Any]]]:
    """Return relative files, aggregate inventory hash, and selected file rows."""
    if not path.exists():
        return [], None, []
    files = sorted(p for p in path.rglob("*") if p.is_file())
    rows: list[dict[str, Any]] = []
    for item in files:
        rel = item.relative_to(path).as_posix()
        # Do not hash very large model/tool directories in this provenance
        # ledger; source datasets and their manifests are always hashed.
        if "/models/" in item.as_posix() or "/tools/" in item.as_posix():
            continue
        rows.append({"relative_path": rel, "size_bytes": item.stat().st_size, "sha256": sha256(item)})
    if not rows:
        return [], None, []
    canonical = "\n".join(f"{r['relative_path']}\t{r['size_bytes']}\t{r['sha256']}" for r in rows)
    return [r["relative_path"] for r in rows], hashlib.sha256(canonical.encode()).hexdigest(), rows


def evidence_paths(source_id: str, local_dir: Path | None) -> list[str]:
    paths: list[str] = ["datasets/data_registry.yaml"]
    if local_dir and local_dir.exists():
        for candidate in ("metadata/acquisition.json", "metadata/manifest.jsonl", "metadata/content_manifest.jsonl", "metadata/content_summary.json"):
            p = local_dir / candidate
            if p.exists():
                paths.append(str(p))
        if source_id == "bgs_onshore_borehole_records":
            paths.extend(str(p) for p in sorted((local_dir / "license").glob("*")) if p.is_file())
    if source_id == "chinese_engineering_borehole_logs":
        paths.extend([
            "configs/datasets/sanming_quarantine_panels_v001.jsonl",
            "docs/data_source_survey.md",
        ])
    return paths


def status_for(record: dict[str, Any], local_dir: Path | None) -> tuple[str, str, list[str]]:
    source_id = record["id"]
    status = str(record.get("status", "")).lower()
    if source_id == "synthetic_borehole_logs_v001":
        return "SYNTHETIC_KNOWN_GT", "INTERNAL_USE", ["synthetic labels are generated by code; no external licence claim"]
    if source_id == "chinese_engineering_borehole_logs":
        return "UNVERIFIED_SOURCE", "QUARANTINE_INTERNAL_ONLY", ["source URLs and item-level terms not captured", "project names/stamps/precise locations may be present"]
    if "conflict" in status or "embargo" in str(record.get("license", "")).lower():
        return "RIGHTS_CONFLICT", "QUARANTINE_INTERNAL_ONLY", ["repository metadata contains conflicting access/licence signals"]
    if "metadata_only" in status or "unverified" in status or "unclear" in status or "needs_manual" in status or "ambiguous" in status:
        return "UNVERIFIED_SOURCE", "USE_WITH_CAUTION" if local_dir and local_dir.exists() else "QUARANTINE_INTERNAL_ONLY", ["file-level rights or content scope are incomplete"]
    if "out_of_scope" in status:
        return "CLAIM_CAPTURED", "USE_WITH_CAUTION", ["format/content is outside the Phase-I page-image contract"]
    return "CLAIM_CAPTURED", "USE_WITH_CAUTION", ["licence claim is recorded from repository metadata; final item/content review remains required"]


def build() -> dict[str, Any]:
    registry = yaml.safe_load((ROOT / "datasets/data_registry.yaml").read_text(encoding="utf-8"))
    records: list[dict[str, Any]] = []
    for source in registry.get("datasets", []):
        sid = source["id"]
        local_dir = LOCAL_DIRS.get(sid)
        files, aggregate, rows = inventory(local_dir) if local_dir else ([], None, [])
        verification_status, decision, risks = status_for(source, local_dir)
        manifest_rows = [r for r in rows if "manifest" in r["relative_path"] or "acquisition" in r["relative_path"]]
        records.append({
            "source_id": sid,
            "source_name": source.get("name"),
            "url": source.get("url"),
            "doi": source.get("doi"),
            "publisher": source.get("source_organization"),
            "retrieval_date": source.get("access_date"),
            "local_paths": [str(local_dir)] if local_dir and local_dir.exists() else [],
            "file_count_in_local_snapshot": len(files),
            "local_snapshot_inventory_sha256": aggregate,
            "manifest_evidence": manifest_rows,
            "access_method": source.get("access_status"),
            "claimed_license": source.get("license"),
            "license_url": source.get("license_url"),
            "verification_status": verification_status,
            "internal_decision": decision,
            "risks": risks,
            "experiments_or_papers": source.get("paper_fit", []),
            "requires_human_check_before_submission": True,
            "evidence": evidence_paths(sid, local_dir),
            "registry_status": source.get("status"),
            "registry_verification_notes": source.get("verification_notes"),
        })

    synthetic = LOCAL_DIRS["synthetic_borehole_logs_v001"]
    files, aggregate, rows = inventory(synthetic)
    records.append({
        "source_id": "synthetic_borehole_logs_v001",
        "source_name": "GeoLogParser programmatically generated borehole logs",
        "url": None,
        "doi": None,
        "publisher": "GeoLogParser project",
        "retrieval_date": "2026-08-13",
        "local_paths": [str(synthetic)],
        "file_count_in_local_snapshot": len(files),
        "local_snapshot_inventory_sha256": aggregate,
        "manifest_evidence": [r for r in rows if r["relative_path"] in {"manifest.jsonl", "summary.json"}],
        "access_method": "generated locally by scripts/generate_synthetic_dataset.py",
        "claimed_license": "project-generated; release licence TBD",
        "license_url": None,
        "verification_status": "SYNTHETIC_KNOWN_GT",
        "internal_decision": "INTERNAL_USE",
        "risks": ["synthetic distribution may not represent real document variation", "release licence and generated font assets require final review"],
        "experiments_or_papers": ["paper1_controlled_robustness", "paper2_constraint_protocol", "paper3_error_propagation_protocol"],
        "requires_human_check_before_submission": True,
        "evidence": ["src/geologparser/synthetic.py", "scripts/generate_synthetic_dataset.py", str(synthetic / "manifest.jsonl")],
        "registry_status": "generated_known_ground_truth",
        "registry_verification_notes": "Ground truth is generated from the renderer input records and is not external human annotation.",
    })

    return {
        "ledger_version": "v001",
        "generated_utc": date.today().isoformat(),
        "purpose": "Pre-submission human verification of every external source used by internal experiments and every synthetic source used for reported protocols.",
        "policy": {
            "rights_unverified_experiment_use": "permitted for internal/provisional work under quarantine and explicit disclosure",
            "public_release_or_submission": "blocked until a human verifies source terms, item scope, privacy, sensitive locations, embedded third-party content, and attribution",
            "machine_labels": "must be called Silver, pseudo-label, or machine-adjudicated; never human/expert Ground Truth without independent evidence",
            "ledger_is_not_a_licence": "recording a source does not grant permission to download, redistribute, or publish it",
        },
        "records": records,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "datasets/source_verification_ledger.yaml")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(yaml.safe_dump(build(), sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
