#!/usr/bin/env python3
"""Regenerate the compact autonomous-research status dashboard."""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import subprocess

import yaml


ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = Path("/data/GeoLogParser/datasets")


def _count_manifest(path: Path, tier: str | None = None) -> int:
    if not path.is_file():
        return 0
    count = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if tier is None or row.get("ground_truth_tier") == tier:
            count += 1
    return count


def main() -> None:
    registry = yaml.safe_load((ROOT / "datasets/data_registry.yaml").read_text(encoding="utf-8"))
    compliance_path = Path("/data/GeoLogParser/artifacts/compliance/automated_compliance_v002.json")
    compliance = json.loads(compliance_path.read_text(encoding="utf-8")) if compliance_path.is_file() else {"decision_counts": {}}
    synthetic_summary_path = DATA_ROOT / "synthetic_borehole_logs_v001/summary.json"
    synthetic = json.loads(synthetic_summary_path.read_text(encoding="utf-8")) if synthetic_summary_path.is_file() else {}
    silver_summary_path = Path("/data/GeoLogParser/artifacts/silver/synthetic_ocr_ab_v001/summary.json")
    silver = json.loads(silver_summary_path.read_text(encoding="utf-8")) if silver_summary_path.is_file() else {}
    padova_silver_summary = Path("/data/GeoLogParser/artifacts/silver/unipd_field_silver_v003/summary.json")
    padova_silver = json.loads(padova_silver_summary.read_text(encoding="utf-8")) if padova_silver_summary.is_file() else {}
    swissgeol_gold_manifests = [
        Path("/data/GeoLogParser/datasets/public/swissgeol_thurgau_paired_v002/gold_interval_manifest_v002.jsonl"),
        Path("/data/GeoLogParser/datasets/public/swissgeol_thurgau_paired_v003/gold_interval_manifest_v003.jsonl"),
    ]
    swissgeol_gold_rows = [
        json.loads(line)
        for manifest in swissgeol_gold_manifests if manifest.is_file()
        for line in manifest.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    authoritative_gold_documents = len(swissgeol_gold_rows)
    authoritative_gold_intervals = sum(
        int(row.get("interval_count", 0)) for row in swissgeol_gold_rows
    )
    readiness = json.loads((ROOT / "docs/generated/publication_readiness.json").read_text(encoding="utf-8"))
    rows = []
    for paper, value in sorted(readiness.get("paper_indexes", {}).items()):
        rows.append((paper, value.get("controlled_formal_experiment_count", 0), value.get("real_formal_experiment_count", 0), value.get("indexed_experiment_count", 0)))
    git_commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, capture_output=True, check=False).stdout.strip()
    lines = [
        "<!-- AUTO-GENERATED by scripts/update_status.py; evidence dashboard, not a paper result. -->",
        "# GeoLogParser Status",
        "",
        f"Git commit: `{git_commit or 'UNCOMMITTED'}`",
        "",
        "## Data tiers",
        "",
        "| Tier | Count | Meaning |",
        "|---|---:|---|",
        "| Human-verified Gold | 0 | No project annotation has yet passed the independent human Ground-Truth gate |",
        f"| Authoritative interval Gold | {authoritative_gold_documents} documents / {authoritative_gold_intervals} intervals | Official database boundaries with exact complete agreement to an explicit table in the paired PDF; interval boundaries only; no human annotation claimed |",
        f"| Authoritative metadata | {readiness.get('paper_indexes', {}).get('paper1', {}).get('eligibility_counts', {}).get('formal_authoritative_metadata', 0)} runs | Official metadata paired with scans; no interval/lithology labels |",
        f"| Silver | {silver.get('source_item_count', 0) + padova_silver.get('source_item_count', 0)} | Machine-adjudicated candidate labels; not Gold |",
        f"| Synthetic | {synthetic.get('count', 0)} | Known programmatic labels; controlled experiments only |",
        f"| Registry entries | {len(registry.get('datasets', []))} | Candidate sources, not page/interval counts |",
        "",
        "## Automated compliance",
        "",
        "`review_type=automated_compliance_review`; `human_reviewed=false`.",
        "",
        "| Decision | Count |",
        "|---|---:|",
    ]
    for decision in ("ELIGIBLE", "ELIGIBLE_INTERNAL_ONLY", "AMBIGUOUS", "EXCLUDE"):
        lines.append(f"| {decision} | {compliance.get('decision_counts', {}).get(decision, 0)} |")
    lines.extend([
        "",
        "## Formal experiments",
        "",
        "| Paper | Controlled formal | Real formal | Indexed runs |",
        "|---|---:|---:|---:|",
    ])
    lines.extend(f"| {paper} | {controlled} | {real} | {indexed} |" for paper, controlled, real, indexed in rows)
    lines.extend([
        "",
        "## Paper status",
        "",
        "- Paper I: `RESULTS_AVAILABLE` for an incremental held-out authoritative source-agreement interval test, authoritative-metadata runs, and explicitly named machine-Silver agreement runs; representative multi-source/template-disjoint interval benchmark `NOT COMPLETED`.",
        "- Paper II: `RESULTS_AVAILABLE` for a real authoritative-metadata abstention study, a controlled Synthetic method ablation, the negative v1 held-out interval test, and a positive frozen v2 held-out interval test with F1 0.857 to 0.921 and FCR 0/4; broader real interval-level component ablation and larger-sample FCR estimation `NOT COMPLETED`.",
        "- Paper III: `RESULTS_AVAILABLE` for a real structured-source controlled spatial comparison and controlled Synthetic downstream comparison; image-derived real-site comparison `NOT COMPLETED`.",
        "",
        "## Boundary",
        "",
        "Synthetic and Silver outputs are never promoted to human Gold. The authoritative",
        "interval tier is limited to source-agreed numeric boundaries and is not described",
        "as human annotation. Automated compliance is limited to captured licence/source",
        "evidence and text metadata; visual privacy, sensitive-location absence, and geological correctness remain",
        "unestablished without the corresponding evidence.",
        "",
    ])
    output = ROOT / "docs/status.md"
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
