#!/usr/bin/env python3
"""Regenerate the compact autonomous-research status dashboard."""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import subprocess

import yaml


ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = Path("/data/GeoLogParser/datasets")


def _count_manifest(path: Path, tier: str | None = None) -> int:
    if not path.is_file():
        return 0
    count = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if tier is None or row.get("ground_truth_tier") == tier:
            count += 1
    return count


def main() -> None:
    registry = yaml.safe_load((ROOT / "datasets/data_registry.yaml").read_text(encoding="utf-8"))
    compliance_path = Path("/data/GeoLogParser/artifacts/compliance/automated_compliance_v002.json")
    compliance = json.loads(compliance_path.read_text(encoding="utf-8")) if compliance_path.is_file() else {"decision_counts": {}}
    synthetic_summary_path = DATA_ROOT / "synthetic_borehole_logs_v001/summary.json"
    synthetic = json.loads(synthetic_summary_path.read_text(encoding="utf-8")) if synthetic_summary_path.is_file() else {}
    silver_summary_path = Path("/data/GeoLogParser/artifacts/silver/synthetic_ocr_ab_v001/summary.json")
    silver = json.loads(silver_summary_path.read_text(encoding="utf-8")) if silver_summary_path.is_file() else {}
    readiness = json.loads((ROOT / "docs/generated/publication_readiness.json").read_text(encoding="utf-8"))
    rows = []
    for paper, value in sorted(readiness.get("paper_indexes", {}).items()):
        rows.append((paper, value.get("formal_experiment_count", 0), value.get("indexed_experiment_count", 0)))
    git_commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, capture_output=True, check=False).stdout.strip()
    lines = [
        "<!-- AUTO-GENERATED by scripts/update_status.py; evidence dashboard, not a paper result. -->",
        "# GeoLogParser Status",
        "",
        f"Git commit: `{git_commit or 'UNCOMMITTED'}`",
        "",
        "## Data tiers",
        "",
        "| Tier | Count | Meaning |",
        "|---|---:|---|",
        f"| Real Gold | 0 | No verified human/public authoritative image-to-interval GT is currently frozen |",
        f"| Silver | {silver.get('source_item_count', 0)} | Machine-adjudicated candidate labels; not Gold |",
        f"| Synthetic | {synthetic.get('count', 0)} | Known programmatic labels; controlled experiments only |",
        f"| Registry entries | {len(registry.get('datasets', []))} | Candidate sources, not page/interval counts |",
        "",
        "## Automated compliance",
        "",
        "`review_type=automated_compliance_review`; `human_reviewed=false`.",
        "",
        "| Decision | Count |",
        "|---|---:|",
    ]
    for decision in ("ELIGIBLE", "ELIGIBLE_INTERNAL_ONLY", "AMBIGUOUS", "EXCLUDE"):
        lines.append(f"| {decision} | {compliance.get('decision_counts', {}).get(decision, 0)} |")
    lines.extend([
        "",
        "## Formal experiments",
        "",
        "| Paper | Formal runs | Indexed runs |",
        "|---|---:|---:|",
    ])
    lines.extend(f"| {paper} | {formal} | {indexed} |" for paper, formal, indexed in rows)
    lines.extend([
        "",
        "## Paper status",
        "",
        "- Paper I: `IMPLEMENTATION` / formal Real Gold benchmark `NOT COMPLETED`.",
        "- Paper II: `IMPLEMENTATION` / formal Gold ablation and calibration `NOT COMPLETED`.",
        "- Paper III: `IMPLEMENTATION` / real spatial Gold downstream comparison `NOT COMPLETED`.",
        "",
        "## Boundary",
        "",
        "Synthetic and Silver outputs are never promoted to human Gold. Automated ",
        "compliance is limited to captured licence/source evidence and text metadata; ",
        "visual privacy, sensitive-location absence, and geological correctness remain ",
        "unestablished without the corresponding evidence.",
        "",
    ])
    output = ROOT / "docs/status.md"
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
